### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by ronanrodrigo** [ronanrodrigo/Sensazonal#1]
# Description
Project stuffs to configure

# Tasks
- [x] Bitrise http://bitrise.io
- [x] Codecov http://codecov.io
- [x] Codebeat http://codebeat.co
- [x] Swiftlint https://github.com/realm/SwiftLint
- [x] Issue template
- [x] Project setup https://github.com/ronanrodrigo/sazonal/projects
