### ISSUE TITLE
Create built in data

### ISSUE THREAD

**Issue by ronanrodrigo** [ronanrodrigo/Sensazonal#4]
In gitlab by @ronanrodrigo on Mar 6, 2018, 18:52

# Description
The first version of Sensazonal will used a built in database with CoreData. Built in data will be all the fruits/vegetables/veggies and their respective months.

# Tasks
* [ ] !1 Core Data setup
* [ ] !1 Create database scheme
* [ ] !2 Create models
* [ ] !2 Create a populated database
