### ISSUE TITLE
List foods by month

### ISSUE THREAD

**Issue by ronanrodrigo** [ronanrodrigo/Sensazonal#5]
In gitlab by @ronanrodrigo on Mar 6, 2018, 21:44

# Description
List all foods from a selected month. By defaul, when open the APP, will be displayed the foods of current month. The list must contains the food **name** and **photo**.

# Prototype
Should be a mosaic list with images and food names like this:

![27D50CD2-5A15-4C14-9FA4-A6055F891B07](/uploads/be275f29d07a5a2bb681fd3bee236fe7/27D50CD2-5A15-4C14-9FA4-A6055F891B07.png)

# Tasks
* [x] !7 Create food list
  * [x] Create collection view
  * [x] Create collection controller
  * [x] Create collection view model
  * [x] Create collection view layout
* [x] Create collection view cell
  * [x] !4 Setup Carthage
  * [x] !5 Create view
  * [x] !5 Tests with `iOSSnapshotTestCase`
* [x] !10 Create month selector
* [x] !3 Create business rules
